export const APP = Object.freeze({
   SET_ERROR: "APP_SET_ERROR",
   REROUTE: "APP_REROUTE",
   SNACKBAR_MESSAGE: "APP_SNACKBAR_MESSAGE",
   OPEN_BACKDROP: "APP_OPEN_BACKDROP",
   SET_SEARCH: "APP_SET_SEARCH",
   SET_START_SEARCH: "APP_SET_START_SEARCH",
   KEY_UP: "APP_KEY_UP",
   KEY_DOWN: "APP_KEY_DOWN",
   CURRENT_INDEX: "APP_CURRENT_INDEX",
   SET_PRELOAD_DONE: "APP_SET_PRELOAD_DONE",
   SET_IN_PROGRESS: "APP_SET_IN_PROGRESS"
});

export const PROFILE = Object.freeze({
   EMPTY: "PROFILE_EMPTY",
   PROPERTY_UPDATE: "PROFILE_PROPERTY_UPDATE"
});

export const LOCAL_LOGIN = Object.freeze({
   IN_PROGRESS: "LOCAL_LOGIN_IN_PROGRESS",
   SUCCESS: "LOCAL_LOGIN_SUCCESS",
   FAILURE: "LOCAL_LOGIN_FAILURE"
});

export const GOOGLE_GET_TOKEN = Object.freeze({
   IN_PROGRESS: "GOOGLE_GET_TOKEN_IN_PROGRESS",
   SUCCESS: "GOOGLE_GET_TOKEN_SUCCESS",
   FAILURE: "GOOGLE_GET_TOKEN_FAILURE"
});

export const INSTAGRAM_GET_TOKEN = Object.freeze({
   IN_PROGRESS: "INSTAGRAM_GET_TOKEN_IN_PROGRESS",
   SUCCESS: "INSTAGRAM_GET_TOKEN_SUCCESS",
   FAILURE: "INSTAGRAM_GET_TOKEN_FAILURE"
});

export const GOOGLE_GET_USER_INFO = Object.freeze({
   IN_PROGRESS: "GOOGLE_GET_USER_INFO_IN_PROGRESS",
   SUCCESS: "GOOGLE_GET_USER_INFO_SUCCESS",
   FAILURE: "GOOGLE_GET_USER_INFO_FAILURE"
});

export const INSTAGRAM_GET_USER_INFO = Object.freeze({
   IN_PROGRESS: "INSTAGRAM_GET_USER_INFO_IN_PROGRESS",
   SUCCESS: "INSTAGRAM_GET_USER_INFO_SUCCESS",
   FAILURE: "INSTAGRAM_GET_USER_INFO_FAILURE"
});

export const REGISTER = Object.freeze({
   IN_PROGRESS: "REGISTER_IN_PROGRESS",
   SUCCESS: "REGISTER_SUCCESS",
   FAILURE: "REGISTER_FAILURE"
});

export const TOKEN_FETCH = Object.freeze({
   IN_PROGRESS: "TOKEN_FETCH_IN_PROGRESS",
   SUCCESS: "TOKEN_FETCH_SUCCESS",
   FAILURE: "TOKEN_FETCH_FAILURE"
});

export const LOGOUT = Object.freeze({
   IN_PROGRESS: "LOGOUT_IN_PROGRESS",
   SUCCESS: "LOGOUT_SUCCESS",
   FAILURE: "LOGOUT_FAILURE"
});

export const PROFILE_UPDATE = Object.freeze({
   IN_PROGRESS: "PROFILE_UPDATE_IN_PROGRESS",
   SUCCESS: "PROFILE_UPDATE_SUCCESS",
   FAILURE: "PROFILE_UPDATE_FAILURE"
});

export const GET_MY_PROFILE = Object.freeze({
   IN_PROGRESS: "GET_MY_PROFILE_IN_PROGRESS",
   SUCCESS: "GET_MY_PROFILE_SUCCESS",
   FAILURE: "GET_MY_PROFILE_FAILURE"
});

export const GET_PROFILE_PICTURE = Object.freeze({
   IN_PROGRESS: "GET_PROFILE_PICTURE _IN_PROGRESS",
   SUCCESS: "GET_PROFILE_PICTURE_SUCCESS",
   FAILURE: "GET_PROFILE_PICTURE_FAILURE"
});

export const UPDATE_PROFILE_PICTURE = Object.freeze({
   IN_PROGRESS: "UPDATE_PROFILE_PICTURE_IN_PROGRESS",
   SUCCESS: "UPDATE_PROFILE_PICTURE_SUCCESS",
   FAILURE: "UPDATE_PROFILE_PICTURE_FAILURE"
});

export const SEARCH_PROFILES = Object.freeze({
   IN_PROGRESS: "SEARCH_PROFILES_IN_PROGRESS",
   SUCCESS: "SEARCH_PROFILES_SUCCESS",
   FAILURE: "SEARCH_PROFILES_FAILURE"
});

export const SEARCH_GIF = Object.freeze({
   IN_PROGRESS: "SEARCH_GIF_IN_PROGRESS",
   SUCCESS: "SEARCH_GIF_SUCCESS",
   FAILURE: "SEARCH_GIF_FAILURE"
});